#!/bin/bash

{
#/usr/lib/mate-notification-daemon/mate-notification-daemon &
#/usr/lib/notify-osd/notify-osd &
#xrandr --output eDP1 --set "Broadcast RGB" "Full" &
dunst &
fbsetbg -l &
#xrdb "$HOME/.Xresources" &
#/usr/lib/notification-daemon-1.0/notification-daemon &
#dunst &
synclient HorizTwoFingerScroll=1 RightButtonAreaTop=0 RightButtonAreaLeft=0 &
#synclient PalmDetect=1 &
#synclient PalmMinWidth=2 &
(xcalib '~/.color/icc/TIANMA_XM.icm'; redshift-gtk)&
#(xcalib -c; xcalib -a -gc 0.8) &
#xcalib -c &
#setxkbmap -option compose:menu &
setxkbmap de neo -option -option compose:menu
pactl upload-sample /usr/share/sounds/freedesktop/stereo/bell.oga bell.ogg
pactl load-module module-x11-bell sample=bell.ogg
xset b 100
#thunderbird &
#kgpg &
keybase-gui &
#export XDG_CURRENT_DESKTOP=GNOME
(xset -dpms; xset s off) &
#gnome-terminal -e 'sh -c "nm-online -t 3600 && exec mosh rpi"' & # -e is deprecated
#compton -b
nm-applet &
cbatticon &
touchegg &
alacritty -e sh -c "nm-online -t 3600 && exec mosh rpi" &
#pulseeffects --gapplication-service &
} > ~/.config/i3/startup.log 2>&1
